/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Frames.AbstractBinaryFrame;
import Frames.AbstractFrame;
import Frames.AbstractSimpleFrame;
import Frames.AndFrame;
import Frames.NotFrame;
import Frames.OrFrame;
import GUI.Dialogs.BinaryFrameViewDialog;
import GUI.Dialogs.ChoiceTypeOfNewFrameDialog;
import GUI.Dialogs.ConceptViewDialog;
import GUI.Dialogs.ConstantViewDialog;
import GUI.Dialogs.NotFrameViewDialog;
import GUI.Dialogs.ViewSimpleFrameDialog;
import GUI.Dialogs.errorDialog;
import ModelInputLoad.InputOutputConDesLan;
import conceptualhierarchy.ActualData;
import conceptualhierarchy.ConceptNode;
import conceptualhierarchy.FrameNode;
import ModelInputLoad.InputOutputXML;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTree;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
import org.xml.sax.SAXException;
import Сoncepts.Concept;

/**
 *
 * @author Anatoly
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        pack();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        frameTree = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        conceptTree = new javax.swing.JTree();
        jLabel2 = new javax.swing.JLabel();
        addFrameButton = new javax.swing.JButton();
        deleteFrameButton = new javax.swing.JButton();
        frameViewButton = new javax.swing.JButton();
        conceptViewButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        removeConceptButton = new javax.swing.JButton();
        constantViewButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        modelMenu = new javax.swing.JMenu();
        generateMenuItem = new javax.swing.JMenuItem();
        clearingMenu = new javax.swing.JMenu();
        clearExtensionalsMenuItem = new javax.swing.JMenuItem();
        removeAllNotDefFramesMenuItem = new javax.swing.JMenuItem();
        removeAllNotUsedConceptsMenuItem = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        clearModelMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Модель предметной области");
        setMinimumSize(new java.awt.Dimension(755, 499));

        updateFrameIsaTree();
        frameTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frameTreeMouseClicked(evt);
            }
        });
        frameTree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                frameTreeKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(frameTree);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Фреймы:");

        updateConceptIsaTree();
        jScrollPane2.setViewportView(conceptTree);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Концепты:");

        addFrameButton.setText("Добавить фрейм");
        addFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFrameButtonActionPerformed(evt);
            }
        });

        deleteFrameButton.setText("Удалить фрейм");
        deleteFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFrameButtonActionPerformed(evt);
            }
        });

        frameViewButton.setText("Просмотреть выбранный фрейм");
        frameViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameViewButtonActionPerformed(evt);
            }
        });

        conceptViewButton.setText("Свойства концепта");
        conceptViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conceptViewButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Добавить концепт");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        removeConceptButton.setText("Удалить концепт");
        removeConceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeConceptButtonActionPerformed(evt);
            }
        });

        constantViewButton.setText("Константы");
        constantViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                constantViewButtonActionPerformed(evt);
            }
        });

        fileMenu.setText("Файл");

        jMenuItem2.setText("Сохранить");
        jMenuItem2.setToolTipText("");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem2);

        jMenuItem1.setText("Загрузить");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);

        jMenuBar1.add(fileMenu);

        modelMenu.setText("Модель");

        generateMenuItem.setText("Генерация элементов");
        generateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateMenuItemActionPerformed(evt);
            }
        });
        modelMenu.add(generateMenuItem);

        clearingMenu.setText("Очистка модели");

        clearExtensionalsMenuItem.setText("Удалить все экстенсионалы");
        clearExtensionalsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearExtensionalsMenuItemActionPerformed(evt);
            }
        });
        clearingMenu.add(clearExtensionalsMenuItem);

        removeAllNotDefFramesMenuItem.setText("Удалить все не def-фреймы");
        removeAllNotDefFramesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAllNotDefFramesMenuItemActionPerformed(evt);
            }
        });
        clearingMenu.add(removeAllNotDefFramesMenuItem);

        removeAllNotUsedConceptsMenuItem.setText("Удалить все неиспользуемые конценты");
        removeAllNotUsedConceptsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAllNotUsedConceptsMenuItemActionPerformed(evt);
            }
        });
        clearingMenu.add(removeAllNotUsedConceptsMenuItem);

        jMenuItem4.setText("Удалить все неиспользуемые константы");
        clearingMenu.add(jMenuItem4);

        clearModelMenuItem.setText("Удалить все (!) элементы ");
        clearModelMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearModelMenuItemActionPerformed(evt);
            }
        });
        clearingMenu.add(clearModelMenuItem);

        modelMenu.add(clearingMenu);

        jMenuBar1.add(modelMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(frameViewButton))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addFrameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteFrameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(constantViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conceptViewButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeConceptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(frameViewButton)
                            .addComponent(conceptViewButton)
                            .addComponent(constantViewButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteFrameButton)
                    .addComponent(addFrameButton)
                    .addComponent(jButton1)
                    .addComponent(removeConceptButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFrameButtonActionPerformed
        ChoiceTypeOfNewFrameDialog chTOfNewWframe = new ChoiceTypeOfNewFrameDialog(this, true);
        chTOfNewWframe.setVisible(true);
        updateFrameIsaTree();
        updateConceptIsaTree();
    }//GEN-LAST:event_addFrameButtonActionPerformed

    private void deleteFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFrameButtonActionPerformed
        // TODO add your handling code here:
        TreeSelectionModel TSM = frameTree.getSelectionModel();
        TreePath TP = TSM.getSelectionPath();
        if (TP == null) 
            return;
        DefaultMutableTreeNode TC = (DefaultMutableTreeNode)TP.getLastPathComponent();
        
        String s = (String) TC.getUserObject();
        if (!s.equals("Frames")) {
            AbstractFrame frame = ActualData.getFrameByName(s);
            if (ActualData.frameIsUsedInDefDemension(frame)){
                new errorDialog(this, true, "Фрейм используется в def-измерении, сначала удалите все его def-концепты!").setVisible(true);
                return;
            }
            else
                ActualData.removeFrameByName(s);
        }
        updateFrameIsaTree();
    }//GEN-LAST:event_deleteFrameButtonActionPerformed

    private void frameTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameTreeMouseClicked
        // TODO add your handling code here:
          
    }//GEN-LAST:event_frameTreeMouseClicked

    private void frameTreeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_frameTreeKeyPressed
        // TODO add your handling code here:
        int extendedKeyCode = evt.getExtendedKeyCode();
        TreeSelectionModel TSM = frameTree.getSelectionModel();
        TreePath TP = TSM.getSelectionPath();
        if (TP == null) 
            return;
        DefaultMutableTreeNode TC = (DefaultMutableTreeNode)TP.getLastPathComponent();
        String s = (String) TC.getUserObject();
        if ((!s.equals("Frames")) && (!(s == null))) {
            AbstractFrame fr = ActualData.getFrameByName(s);
            viewFrame(fr);
        }
    }//GEN-LAST:event_frameTreeKeyPressed
 
    private void frameViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameViewButtonActionPerformed
        // TODO add your handling code here:
        TreeSelectionModel TSM = frameTree.getSelectionModel();
        TreePath TP = TSM.getSelectionPath();
        if (TP == null)  
            return;
        DefaultMutableTreeNode TC = (DefaultMutableTreeNode)TP.getLastPathComponent();
        String s = (String) TC.getUserObject();
        if ((!s.equals("Frames")) && (!(s == null))) {
            AbstractFrame fr = ActualData.getFrameByName(s);
            viewFrame(fr);
        }
        updateConceptIsaTree();
    }//GEN-LAST:event_frameViewButtonActionPerformed

    private void conceptViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conceptViewButtonActionPerformed
        // TODO add your handling code here:
        
        TreeSelectionModel TSM = conceptTree.getSelectionModel();
        TreePath TP = TSM.getSelectionPath();
        if (TP == null)  
            return;
        DefaultMutableTreeNode TC = (DefaultMutableTreeNode)TP.getLastPathComponent();
        String s = (String) TC.getUserObject();
        if (!s.equals("Concepts")) {
            Concept conc = ActualData.getConceptByName(s);
            ConceptViewDialog cwd = new ConceptViewDialog(this, true);
            cwd.setConcept(conc);
            cwd.setVisible(true);
        }
        updateFrameIsaTree();
        updateConceptIsaTree();
    }//GEN-LAST:event_conceptViewButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConceptViewDialog cwd = new ConceptViewDialog(this, true);
        
        cwd.setVisible(true);
        updateFrameIsaTree();
        updateConceptIsaTree();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void constantViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_constantViewButtonActionPerformed
        // TODO add your handling code here:
        TreeSelectionModel TSM = conceptTree.getSelectionModel();
        TreePath TP = TSM.getSelectionPath();
        if (TP == null) 
            return;
        DefaultMutableTreeNode TC = (DefaultMutableTreeNode)TP.getLastPathComponent();
        String s = (String) TC.getUserObject();
        if (!s.equals("Concepts")) {
            Concept conc = ActualData.getConceptByName(s);
            ConstantViewDialog cwd = new ConstantViewDialog(this, true);
            cwd.setConcept(conc);
            cwd.setVisible(true);
        }
        
    }//GEN-LAST:event_constantViewButtonActionPerformed

    private void removeConceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeConceptButtonActionPerformed
        // TODO add your handling code here:
        TreeSelectionModel TSM = conceptTree.getSelectionModel();
        TreePath TP = TSM.getSelectionPath();
        if (TP == null)  
            return;
        DefaultMutableTreeNode TC = (DefaultMutableTreeNode)TP.getLastPathComponent();
        String s = (String) TC.getUserObject();
        if (!s.equals("Concepts")) {
            if (ActualData.conceptIsUsed(ActualData.getConceptByName(s))){
                String errMess ="Концепт задействован во фреймах или является базой для def-концептов, сначала удалите их!";
                errorDialog errorD = new errorDialog(new javax.swing.JFrame(), true, errMess);
                errorD.setVisible(true);
                return;
            }
            ActualData.removeConceptByName(s);
            updateFrameIsaTree();
            updateConceptIsaTree();
        }
    }//GEN-LAST:event_removeConceptButtonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filterXml = new FileNameExtensionFilter(".xml","xml");
        FileNameExtensionFilter filterConDesLan = new FileNameExtensionFilter(".condeslan","condeslan");
        JFileChooser fc = new JFileChooser();
        fc.removeChoosableFileFilter(fc.getFileFilter());
        fc.setFileFilter(filterConDesLan);
        fc.setFileFilter(filterXml);
        String absolutePath;
        if ( fc.showSaveDialog(null) == JFileChooser.APPROVE_OPTION ) {
            absolutePath = fc.getSelectedFile().getAbsolutePath().trim();
            FileFilter acceptedFilter = fc.getFileFilter();
            String extensionDescr = acceptedFilter.getDescription();
            switch (extensionDescr) {
                case ".xml":
                    if (!absolutePath.endsWith(".xml"))
                        absolutePath+=".xml";
                    try {
                        ActualData.save(absolutePath);} 
                    catch (ParserConfigurationException | SAXException | IOException ex) {
                        new errorDialog(this, true, "Ошибка при сохранении файла!").setVisible(true);}
                    break;
                case ".condeslan":{
                    if (!absolutePath.endsWith(".condeslan"))
                        absolutePath+=".condeslan";
                    try {
                        InputOutputConDesLan.save(absolutePath);
                    } catch (IOException ex) {
                        new errorDialog(this, true, "Ошибка при сохранении файла!").setVisible(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FileNameExtensionFilter filterXml = new FileNameExtensionFilter(".xml","xml");
        FileNameExtensionFilter filterConDesLan = new FileNameExtensionFilter(".condeslan","condeslan");
        JFileChooser fc = new JFileChooser();
        fc.removeChoosableFileFilter(fc.getFileFilter());
        fc.setFileFilter(filterConDesLan);
        fc.setFileFilter(filterXml);
        int ret = fc.showDialog(null, "Открыть файл");
        String absolutePath;
        if (ret == JFileChooser.APPROVE_OPTION) {
            absolutePath = fc.getSelectedFile().getAbsolutePath().trim();
            FileFilter acceptedFilter = fc.getFileFilter();
            String extensionDescr = acceptedFilter.getDescription();
            switch (extensionDescr) {
                case ".xml":
                    if (!absolutePath.endsWith(".xml"))
                        absolutePath+=".xml";
                    try {
                        InputOutputXML.load(absolutePath);} 
                    catch (SAXException | IOException ex) {
                        new errorDialog(this, true, "Ошибка при загрузке модели из файла!").setVisible(true);}
                    break;
                case ".condeslan":{
                    if (!absolutePath.endsWith(".condeslan"))
                        absolutePath+=".condeslan";
                    try {
                        InputOutputConDesLan.load(absolutePath);
                    } catch (IOException ex) {
                        new errorDialog(this, true, "Ошибка при загрузке модели из файла!").setVisible(true);
                    }
                }
            }
            updateFrameIsaTree();
            updateConceptIsaTree();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void clearModelMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearModelMenuItemActionPerformed
        ActualData.clear();
        updateFrameIsaTree();
        updateConceptIsaTree();
    }//GEN-LAST:event_clearModelMenuItemActionPerformed

    private void clearExtensionalsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearExtensionalsMenuItemActionPerformed
        // TODO add your handling code here:
        ActualData.clearExtensionals();
    }//GEN-LAST:event_clearExtensionalsMenuItemActionPerformed

    private void generateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generateMenuItemActionPerformed

    private void removeAllNotDefFramesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAllNotDefFramesMenuItemActionPerformed
        // TODO add your handling code here:
        ActualData.removeAllNotDefFrames();
        updateFrameIsaTree();
        updateConceptIsaTree();
    }//GEN-LAST:event_removeAllNotDefFramesMenuItemActionPerformed

    private void removeAllNotUsedConceptsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAllNotUsedConceptsMenuItemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_removeAllNotUsedConceptsMenuItemActionPerformed
    public static void viewFrame(AbstractFrame fr){
        if (fr instanceof AndFrame){
            BinaryFrameViewDialog frViewDialog = new BinaryFrameViewDialog(new javax.swing.JFrame(), true);
            frViewDialog.setFrame((AbstractBinaryFrame) fr); 
            frViewDialog.setVisible(true);
        }
        else if (fr instanceof OrFrame){
            BinaryFrameViewDialog frViewDialog = new BinaryFrameViewDialog(new javax.swing.JFrame(), true);
            frViewDialog.setFrame((AbstractBinaryFrame) fr);
            frViewDialog.setVisible(true);
        }
        else if (fr instanceof AbstractSimpleFrame) {
            ViewSimpleFrameDialog frViewDialog = new ViewSimpleFrameDialog(new javax.swing.JFrame(), true);
            frViewDialog.setFrame((AbstractSimpleFrame) fr);
            frViewDialog.setVisible(true);
        }
        else if (fr instanceof NotFrame){
            NotFrameViewDialog frViewDialog = new NotFrameViewDialog(new javax.swing.JFrame(), true);
            frViewDialog.setFrame((NotFrame) fr);
            frViewDialog.setVisible(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //AbstractSimpleFrame.main(args);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFrameButton;
    private javax.swing.JMenuItem clearExtensionalsMenuItem;
    private javax.swing.JMenuItem clearModelMenuItem;
    private javax.swing.JMenu clearingMenu;
    private javax.swing.JTree conceptTree;
    private javax.swing.JButton conceptViewButton;
    private javax.swing.JButton constantViewButton;
    private javax.swing.JButton deleteFrameButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTree frameTree;
    private javax.swing.JButton frameViewButton;
    private javax.swing.JMenuItem generateMenuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu modelMenu;
    private javax.swing.JMenuItem removeAllNotDefFramesMenuItem;
    private javax.swing.JMenuItem removeAllNotUsedConceptsMenuItem;
    private javax.swing.JButton removeConceptButton;
    // End of variables declaration//GEN-END:variables

    private DefaultMutableTreeNode getFrameHierarchyTree(FrameNode node){
        ArrayList<FrameNode> childNodes = node.getChildNodes();
        DefaultMutableTreeNode root = new DefaultMutableTreeNode(node.getValue().getName());  
        for (FrameNode child: childNodes){
            DefaultMutableTreeNode childNode = getFrameHierarchyTree(child);  
            root.add(childNode);
        }
        return root;
    }
    private DefaultMutableTreeNode getConceptHierarchyTree(ConceptNode node){
        ArrayList<ConceptNode> childNodes = node.getChildNodes();
        DefaultMutableTreeNode root = new DefaultMutableTreeNode(node.getValue().getName());   
        for (ConceptNode child: childNodes){
            DefaultMutableTreeNode childNode = getConceptHierarchyTree(child);  
            root.add(childNode);
        }
        return root;
    }
    private void updateFrameIsaTree(){
        frameTree = new JTree(getFrameHierarchyTree(ActualData.getFrameHoerarchy()));
        jScrollPane1.setViewportView(frameTree);
    }
    private void updateConceptIsaTree(){
        conceptTree = new JTree(getConceptHierarchyTree(ActualData.getConceptHoerarchy()));
        jScrollPane2.setViewportView(conceptTree);
    }
}
