/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Dialogs;

import Generator.Generator;
import conceptualhierarchy.ActualData;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JFrame;
import Сoncepts.Concept;
import Сoncepts.DefConcept;

/**
 *
 * @author Anatoly
 */
public class GenerateDialog extends javax.swing.JDialog {

    /**
     * Creates new form GenerateDialog
     * @param parent
     * @param modal
     */
    public GenerateDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        conceptChooseComboBox.removeAllItems();
        conceptChooseComboBox.addItem("All concepts");
        for (Concept  concept: ActualData.getConcepts())
            if (!(concept instanceof DefConcept))
                conceptChooseComboBox.addItem(concept.getName());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        constantCountMinTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        conceptChooseComboBox = new javax.swing.JComboBox();
        constantGenerateButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        constantCountMaxTextField = new javax.swing.JTextField();
        conceptNestingProbabilityTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        conceptCountTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        conceptGenerateButton = new javax.swing.JButton();
        frameNestingProbabilityTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        framesCountTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        frameGenerateButton = new javax.swing.JButton();
        slotCountTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Генерация элементов");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Параметры:");

        jLabel2.setText("Количство констант:");

        jLabel3.setText("Концепт:");

        conceptChooseComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        constantGenerateButton.setText("Сгенерировать!");
        constantGenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                constantGenerateButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("-");

        jLabel6.setText("Вероятность вложенности (в процентах):");

        jLabel8.setText("Количество концептов:");

        conceptGenerateButton.setText("Сгенерировать!");
        conceptGenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conceptGenerateButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Вероятность вложенности (в процентах):");

        jLabel7.setText("Количество фреймов:");

        frameGenerateButton.setText("Сгенерировать!");
        frameGenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameGenerateButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Количество слотов:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(constantGenerateButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(conceptChooseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(constantCountMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(constantCountMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(conceptGenerateButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(framesCountTextField)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(frameNestingProbabilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(conceptCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(conceptNestingProbabilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(frameGenerateButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(slotCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(constantCountMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(conceptChooseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(constantCountMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(constantGenerateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conceptNestingProbabilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(conceptCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conceptGenerateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frameNestingProbabilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(framesCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slotCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(frameGenerateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void constantGenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_constantGenerateButtonActionPerformed
        // TODO add your handling code here:
        String location = conceptChooseComboBox.getSelectedItem().toString();
        String constantCountMinTextFieldValue = constantCountMinTextField.getText().trim();
        String constantCountMaxTextFieldValue = constantCountMaxTextField.getText().trim();
        int constantCountMin, constantCountMax;
        try{
            constantCountMin = Integer.valueOf(constantCountMinTextFieldValue);
            constantCountMax = Integer.valueOf(constantCountMaxTextFieldValue);
            if (constantCountMin>constantCountMax)
                throw new NumberFormatException();
            Generator.generateConstants(location, constantCountMin, constantCountMax);
            ErrorDialog errD = new ErrorDialog(new JFrame(), true, "Константы сгенерированы!");
            errD.setTitle("Сгенерировано");
            errD.setVisible(true);
        }
        catch (NumberFormatException ex){
            new ErrorDialog(new JFrame(), true, "Некорректный ввод!").setVisible(true);
        }
    }//GEN-LAST:event_constantGenerateButtonActionPerformed

    private void conceptGenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conceptGenerateButtonActionPerformed
        // TODO add your handling code here:
        String conceptCountFieldValue = conceptCountTextField.getText().trim();
        String nestingProbabilityFieldValue = conceptNestingProbabilityTextField.getText().trim();
        try{
            int conceptCount = Integer.valueOf(conceptCountFieldValue);
            int nestingProbability = Integer.valueOf(nestingProbabilityFieldValue);
            if (conceptCount <= 0 || nestingProbability < 0 || nestingProbability > 100)
                throw new NumberFormatException();
            Generator.generateConcepts(conceptCount, nestingProbability);
            ErrorDialog errD = new ErrorDialog(new JFrame(), true, "Концепты сгенерированы!");
            errD.setTitle("Сгенерировано");
            errD.setVisible(true);
        }
        catch (NumberFormatException ex){
            new ErrorDialog(new JFrame(), true, "Некорректный ввод!").setVisible(true);
        }
    }//GEN-LAST:event_conceptGenerateButtonActionPerformed

    private void frameGenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameGenerateButtonActionPerformed
        // TODO add your handling code here:
        String countFieldValue = framesCountTextField.getText().trim();
        String nestingProbabilityFieldValue = frameNestingProbabilityTextField.getText().trim();
        String slotCountFiledValue = slotCountTextField.getText().trim();
        try{
            int framesCount = Integer.valueOf(countFieldValue);
            int nestingProbability = Integer.valueOf(nestingProbabilityFieldValue);
            int slotCount = Integer.valueOf(slotCountFiledValue);
            if (framesCount <= 0 || nestingProbability < 0 || nestingProbability > 100 || slotCount <= 0)
                throw new NumberFormatException();
            if (ActualData.getConcepts().isEmpty()){
                new ErrorDialog(new JFrame(), true, "Нет концептов для использования в качестве доменов!").setVisible(true);
                return;
            }
            Generator.generateSimpleFrames(framesCount, nestingProbability, slotCount); 
            ErrorDialog errD = new ErrorDialog(new JFrame(), true, "Фреймы сгенерированы!");
            errD.setTitle("Сгенерировано");
            errD.setVisible(true);
        }
        catch (NumberFormatException ex){
            new ErrorDialog(new JFrame(), true, "Некорректный ввод!").setVisible(true);
        }
    }//GEN-LAST:event_frameGenerateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GenerateDialog dialog = new GenerateDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox conceptChooseComboBox;
    private javax.swing.JTextField conceptCountTextField;
    private javax.swing.JButton conceptGenerateButton;
    private javax.swing.JTextField conceptNestingProbabilityTextField;
    private javax.swing.JTextField constantCountMaxTextField;
    private javax.swing.JTextField constantCountMinTextField;
    private javax.swing.JButton constantGenerateButton;
    private javax.swing.JButton frameGenerateButton;
    private javax.swing.JTextField frameNestingProbabilityTextField;
    private javax.swing.JTextField framesCountTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField slotCountTextField;
    // End of variables declaration//GEN-END:variables
}
